class PlatformRepository {
  static const Map<String, String> platformNames = {
    "appStore": "Apple App Store",
    "epicGames": "Epic Games Store",
    "gog": "GOG",
    "humbleBundle": "Humble Bundle",
    "itchio": "itch.io",
    "playStore": "Google Play Store",
    "playstation": "PlayStation",
    "questStore": "Meta Quest Store",
    "steam": "Steam",
    "switch": "Nintendo Switch",
    "xbox": "Xbox",
    "amazon": "Amazon",
    "driveThru": "DriveThruRPG",
    "gameCrafter": "The Game Crafter",
    "fdroid": "F-Droid",
    "github": "GitHub",
    "gitlab": "GitLab",
    "productHunt": "Product Hunt",
    "artstation": "ArtStation",
    "cgtrader": "CGTrader",
    "cults3d": "Cults3D",
    "fab": "Fab",
    "figma": "Figma Community",
    "gumroad": "Gumroad",
    "printables": "Printables",
    "sketchfab": "Sketchfab",
    "superhive": "Superhive",
    "thingiverse": "Thingiverse",
    "unityAssetStore": "Unity Asset Store",
    "appleBooks": "Apple Books",
    "audible": "Audible",
    "googlePlayBooks": "Google Play Books",
    "medium": "Medium",
    "royalRoad": "Royal Road",
    "substack": "Substack",
    "tapas": "Tapas",
    "wattpad": "Wattpad",
    "webtoon": "Webtoon",
    "appleMusic": "Apple Music",
    "bandcamp": "Bandcamp",
    "beatstars": "Beatstars",
    "soundcloud": "SoundCloud",
    "spotify": "Spotify",
    "nebula": "Nebula",
    "vimeo": "Vimeo",
    "amazonHandmade": "Amazon Handmade",
    "bigCartel": "Big Cartel",
    "etsy": "Etsy",
    "redBubble": "Redbubble",
    "society6": "Society6",
    "bsky": "Bluesky",
    "discord": "Discord",
    "instagram": "Instagram",
    "kick": "Kick",
    "kofi": "Ko-fi",
    "linkedin": "LinkedIn",
    "linktree": "Linktree",
    "mailList": "Mailing List",
    "mastodon": "Mastodon",
    "patreon": "Patreon",
    "reddit": "Reddit",
    "threads": "Threads",
    "tiktok": "TikTok",
    "tumblr": "Tumblr",
    "twitch": "Twitch",
    "twitter": "X",
    "web": "Website",
    "youtube": "YouTube",
    "backerkit": "BackerKit",
    "crowdSupply": "Crowd Supply",
    "gamefound": "Gamefound",
    "indiegogo": "Indiegogo",
    "kickstarter": "Kickstarter",
  };

  static String getPlatformName(String key) {
    return platformNames[key] ?? key;
  }
}
